// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFB4Bn7L787zFnQA--ma4khPLKy7LWI28',
    appId: '1:805249062643:web:c1c3339f5ff88b53b6c986',
    messagingSenderId: '805249062643',
    projectId: 'bmicalc-7ca3c',
    authDomain: 'bmicalc-7ca3c.firebaseapp.com',
    storageBucket: 'bmicalc-7ca3c.firebasestorage.app',
    measurementId: 'G-T8JHCVW5ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr_1Yc9OnwHlJW4bi660nz6Uu39YWf808',
    appId: '1:805249062643:android:dfca3ef096ad6144b6c986',
    messagingSenderId: '805249062643',
    projectId: 'bmicalc-7ca3c',
    storageBucket: 'bmicalc-7ca3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmrmiTGpFvNUndgK1nm2LNDLoNUjpW9vI',
    appId: '1:805249062643:ios:0e71afdd3a634b85b6c986',
    messagingSenderId: '805249062643',
    projectId: 'bmicalc-7ca3c',
    storageBucket: 'bmicalc-7ca3c.firebasestorage.app',
    iosBundleId: 'com.example.bmiApp',
  );
}
